apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ repo_name | mandatory }} -cluster-jobmanager-prod
  namespace: {{ namespace or "flink-assignment" }}
spec:
  replicas: {{ jobmanager_replicas or 1 }}
  selector:
    matchLabels:
      app: {{ labels_app  or "flink" }}
      cluster: {{ labels_cluster or  repo_name }} -cluster
      component: {{ labels_component or "jobmanager"}}
      track: {{ labels_track or "prod" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ maxSurge or 1 }}
      maxUnavailable: {{ maxUnavailable or 0 }}
  template:
    metadata:
      labels:
        app: {{ labels_app  or "flink" }}
        cluster: {{ labels_cluster or repo_name }} -cluster
        component: {{ labels_component or "jobmanager"}}
        track: {{ labels_track or "prod" }}
    spec:
      containers:
      - name: {{ name or "jobmanager" }}
        image: {{ image or "docker_image" }}
        imagePullPolicy: {{ imagePullPolicy or "Always" }}
        args: ["jobmanager"]
        resources:
          requests:
            cpu: {{ cpu or "100.0" }}
            memory: {{ memory or "300Gi"}}
          limits:
            cpu: {{ cpu or  "100.0" }}
            memory: {{ memory or "300Gi" }}
        ports:
        - containerPort: {{ rpc_jobmanager_container_port or 6123}}
          name: rpc
        - containerPort: {{ blob_jobmanager_container_port or 6124}}
          name: blob
        - containerPort: {{ query_jobmanager_container_port or 6125}}
          name: query
        - containerPort: {{ ui_jobmanager_container_port or 8081}}
          name: ui
        - containerPort: {{ metrics_jobmanager_container_port or 9610}}
          name: metrics
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: {{ JOB_MANAGER_RPC_ADDRESS or repo_name}} -cluster-jobmanager-prod
        - name: HADOOP_USER_NAME
          value: {{ HADOOP_USER_NAME or "yarn"}}
        - name: JOB_MANAGER_MEMORY
          value: {{ JOB_MANAGER_MEMORY or "1000m" }}
        - name: HADOOP_CONF_DIR
          value: {{  HADOOP_CONF_DIR or "/etc/hadoop/conf" }}
        - name: TRACK
          value: {{ TRACK or "prod" }}
